version: 1.2
workflows:
  - name: "jpl-uads-test"
    subclass: CWL
    publish: true
    primaryDescriptorPath: /test.cwl
    testParameterFiles:
      - "/no_input.json"
    authors:
      - name: "Nick LaHaye"
        email: "nlahaye@jpl.nasa.gov"
    name: jpl-uads-test


